from .config import (
    MSG_PAGO_EXITOSO,
    MSG_PAGO_FALLIDO,
    MSG_PAGO_REEMBOLSADO,
    MSG_NO_PAGO_COMPENSAR,
    ESTADO_APROBADO,
    ESTADO_REEMBOLSADO,
    PROBABILIDAD_EXITO,
    SERVICE_NAME)