from .config import (
    ESTADO_CONFIRMADA,
    ESTADO_CANCELADA,
    MSG_COMPRA_EXITOSA,
    MSG_COMPRA_FALLIDA,
    MSG_COMPRA_CANCELADA,
    MSG_NO_COMPRA_COMPENSAR,
    PROBABILIDAD_EXITO,
    SERVICE_NAME)